checks:
  - index: 1
    name: "ns1"
    command: "cat file1.txt | grep -q true"
  - index: 2
    name: "ns2"
    command: "cat file2.txt | grep -q true"
  - index: 3
    name: "ns3"
    command: "cat file3.txt | grep -q true"
  - index: 4
    name: "ns4"
    command: "cat file4.txt | grep -q true"
  - index: 5
    name: "ns5"
    command: "cat file5.txt | grep -q true"
  - index: 6
    name: "ns6"
    command: "cat file6.txt | grep -q true"